import "server-only";
import type { createClient } from "@/lib/supabase/server";

type Supabase = Awaited<ReturnType<typeof createClient>>;

async function checksum(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as unknown as ArrayBuffer);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Files Walkup generates (a filled tax packet, a worksheet) go into the
 * association's Document Hub like any upload: same bucket, same tenancy path,
 * same row, filed under a category and linked to what they're about. An
 * identical file already stored is reused rather than duplicated. Runs as the
 * signed-in board member — RLS decides, not this function.
 */
export async function storeGeneratedDocument(
  supabase: Supabase,
  opts: {
    associationId: string;
    bytes: Uint8Array;
    filename: string;
    mimeType: string;
    categorySlug: string;
    title: string;
    link?: { targetTable: string; targetId: string; relation: string };
  },
): Promise<{ id: string } | { error: string }> {
  const digest = await checksum(opts.bytes);
  const { data: existing } = await supabase
    .from("documents")
    .select("id")
    .eq("checksum", digest)
    .is("deleted_at", null)
    .limit(1);
  let id = existing?.[0]?.id as string | undefined;

  if (!id) {
    const { data: cats } = await supabase
      .from("document_categories")
      .select("id, default_visibility")
      .eq("association_id", opts.associationId)
      .eq("slug", opts.categorySlug)
      .limit(1);
    const safeName = opts.filename.replace(/[^\w.\-]+/g, "_").slice(-120);
    const path = `${opts.associationId}/${Date.now()}-${safeName}`;
    const { error: uploadError } = await supabase.storage
      .from("documents")
      .upload(path, new Blob([opts.bytes as unknown as ArrayBuffer], { type: opts.mimeType }), { contentType: opts.mimeType });
    if (uploadError) return { error: uploadError.message };

    const { data: doc, error } = await supabase
      .from("documents")
      .insert({
        association_id: opts.associationId,
        storage_path: path,
        filename: opts.filename,
        title: opts.title,
        mime_type: opts.mimeType,
        byte_size: opts.bytes.byteLength,
        checksum: digest,
        category_id: cats?.[0]?.id ?? null,
        visibility: cats?.[0]?.default_visibility ?? "board_only",
        tag_source: "manual",
        source: "import",
        extraction_state: "skipped",
        extraction_error: "Generated by Walkup — nothing to read.",
      })
      .select("id")
      .single();
    if (error || !doc) {
      await supabase.storage.from("documents").remove([path]);
      return { error: error?.message ?? "The file couldn't be saved." };
    }
    id = doc.id as string;
  }

  if (opts.link) {
    await supabase.from("document_links").upsert(
      {
        association_id: opts.associationId,
        document_id: id,
        target_table: opts.link.targetTable,
        target_id: opts.link.targetId,
        relation: opts.link.relation,
      },
      { onConflict: "document_id,target_table,target_id,relation", ignoreDuplicates: true },
    );
  }
  return { id };
}
